workflows:
  ios-workflow:
    name: SiteNative iOS without OneSignal
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: M8H6M62QRS
        APP_STORE_CONNECT_KEY_IDENTIFIER: 977643VZ2N
        APP_STORE_CONNECT_PRIVATE_KEY: |-
         -----BEGIN PRIVATE KEY-----
         MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLw/DAi9YbYmFHKuq
         ZCI/ule935+rLu2JzbFY5QIPWIqgCgYIKoZIzj0DAQehRANCAATt8XH7bY75gtAv
         vHSyizT/fo0MwhQlK3ZkxdH/tYv98jV5yjYFRNo8iORSWrLDSZCTKnBHty1g0Bky
         jfmS6GZ8
         -----END PRIVATE KEY-----

        CERTIFICATE_PRIVATE_KEY: |-
         

        BUNDLE_ID: "app.idopk.ru"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --log-api-calls --verbose
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number={APP_VERSION} \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      scripts:
        - name: HTTP notification
          script: |
            curl https://app.startapp.pro/backend/api/observe/notice/3e2ace32-5636-3e9c-28ef-2dd1b0469f03